/* 
  mod_isucon.c -- Apache isucon module
  [Autogenerated via ``apxs -n isucon -g'']

    $ apxs -c -i mod_isucon.c

    #   httpd.conf
    LoadModule isucon_module modules/mod_isucon.so
    <Location /isucon>
    SetHandler isucon
    </Location>
*/ 

#include "httpd.h"
#include "http_log.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "apr_tables.h"
#include "apr_strings.h"

typedef struct {
    char *dbname;
    char *host;
    char *port;
    char *username;
    char *password;

    int  pool;
} isucon_config_t;

module AP_MODULE_DECLARE_DATA isucon_module;

static void *create_dir_config(apr_pool_t *p, char *dir)
{
    isucon_config_t *config = (isucon_config_t *)apr_palloc(p, sizeof(isucon_config_t));

    return config;
}

static const char *set_dbname(cmd_parms *parms, void *mconfig, const char *w)
{
    isucon_config_t *config = (isucon_config_t *)mconfig;

    config->dbname = apr_pstrdup(parms->pool, w);

    return NULL;
}

static const command_rec isucon_cmds[] =
{
  AP_INIT_TAKE1("dbname", set_dbname, NULL, OR_ALL, "Not dbname."),
  {NULL}
};


static apr_table_t *parse_post(request_rec *r, const char *query_string)
{
    apr_table_t *table;
    const char *key;
    const char *val;

    table = apr_table_make(r->pool, 8);

    if (query_string == NULL) {
        return table;
    }

    while(*query_string && (val = ap_getword(r->pool, &query_string, '&'))){
        key = ap_getword(r->pool, &val, '=');

        ap_unescape_url((char*)key);
        ap_unescape_url((char*)val);
        apr_table_merge(table, key, val);
    }

    return table;
}

static void dump_query_string(request_rec *r, const apr_table_t *table)
{
    const apr_array_header_t *arr;
    apr_table_entry_t *entry;
    int i;

    arr = apr_table_elts(table);

    for (i = 0; i < arr->nelts; i++) {
        entry = (apr_table_entry_t *)(arr->elts + (arr->elt_size * i));
        ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, "  key=[%s], val=[%s]", entry->key, entry->val);
    }

    return;
}

/* The sample content handler */
static int isucon_handler(request_rec *r)
{
    if (strcmp(r->handler, "isucon")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (r->header_only)
        return OK;

    {
        apr_table_t *table = parse_post(r, r->args);

        dump_query_string(r, table);
    }

    {
//        isucon_config_t *config = (isucon_config_t *)ap_get_module_config(r->per_dir_config, &isucon_module);
    }

    ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, "args: %s", r->args);
    ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, "uri: %s", r->uri);
    ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, "unparsed uri: %s", r->unparsed_uri);

    ap_rputs("The sample page from mod_isucon.c\n", r);
    return OK;
}

static void isucon_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(isucon_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA isucon_module = {
    STANDARD20_MODULE_STUFF, 
    create_dir_config,     /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    isucon_cmds,           /* table of config file commands       */
    isucon_register_hooks  /* register hooks                      */
};

